# Generated by Django 6.0.3 on 2026-04-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='deadline',
            field=models.TimeField(default='18:00'),
        ),
    ]
